# Generated by Django 6.0.2 on 2026-03-19 06:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OUT_SIDE_FACTORY', 'OUT_SIDE_FACTORY'), ('ON_THE_WAY', 'ON_THE_WAY'), ('UNDER_LOADING', 'UNDER_LOADING'), ('AT_REFINERY', 'AT_REFINERY'), ('OTW_TO_REFINERY', 'OTW_TO_REFINERY'), ('KANDLA_STORAGE', 'KANDLA_STORAGE'), ('MUNDRA_PORT', 'MUNDRA_PORT'), ('ON_THE_SEA', 'ON_THE_SEA'), ('IN_CONTRACT', 'IN_CONTRACT'), ('COMPLETED', 'COMPLETED'), ('DELIVERED', 'DELIVERED'), ('IN_TRANSIT', 'IN_TRANSIT'), ('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('IN_TANK', 'IN_TANK')], max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default='0.00', editable=False, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_litre', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('transporter', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('eta', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'stock_status',
            },
        ),
        migrations.CreateModel(
            name='StockStatusUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.CharField(max_length=255)),
                ('new_value', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'stock_update_logs',
            },
        ),
    ]
