# Generated by Django 6.0.2 on 2026-02-26 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sap_sync', '0006_alter_products_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OUT_SIDE_FACTORY', 'OUT_SIDE_FACTORY'), ('ON_THE_WAY', 'ON_THE_WAY'), ('UNDER_LOADING', 'UNDER_LOADING'), ('AT_REFINERY', 'AT_REFINERY'), ('OTW_TO_REFINERY', 'OTW_TO_REFINERY'), ('KANDLA_STORAGE', 'KANDLA_STORAGE'), ('MUNDRA_PORT', 'MUNDRA_PORT'), ('ON_THE_SEA', 'ON_THE_SEA'), ('IN_CONTRACT', 'IN_CONTRACT'), ('COMPLETED', 'COMPLETED'), ('DELIVERED', 'DELIVERED'), ('IN_TRANSIT', 'IN_TRANSIT'), ('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING')], max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('deleted', models.BooleanField(default=False)),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sap_sync.products')),
                ('vendor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sap_sync.party')),
            ],
            options={
                'db_table': 'stock_status',
            },
        ),
    ]
