# Generated by Django 6.0.2 on 2026-03-19 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sap_sync', '0001_initial'),
        ('stock', '0001_initial'),
        ('tank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstatus',
            name='item_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tank.tankitem'),
        ),
        migrations.AddField(
            model_name='stockstatus',
            name='vendor_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sap_sync.party', to_field='card_code'),
        ),
        migrations.AddField(
            model_name='stockstatusupdatelog',
            name='stock_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stockstatus'),
        ),
    ]
