# Generated by Django 6.0.2 on 2026-02-26 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0007_rmproducts_rename_products_fgproducts_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstatus',
            name='item_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sap_sync.rmproducts'),
        ),
    ]
