# Generated by Django 6.0.2 on 2026-02-27 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stockstatus_item_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockStatusUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=30)),
                ('old_value', models.CharField(max_length=30)),
                ('new_value', models.CharField(max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=30)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.stockstatus')),
            ],
            options={
                'db_table': 'stock_update_logs',
            },
        ),
    ]
