# Generated by Django 6.0.2 on 2026-03-21 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0002_alter_fgproducts_category_alter_fgproducts_item_code_and_more'),
        ('stock', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstatus',
            name='is_accumulator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockstatus',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='stock.stockstatus'),
        ),
        migrations.AddField(
            model_name='stockstatus',
            name='remainder_action',
            field=models.CharField(blank=True, choices=[('RETAIN', 'Retain — reduce parent, keep alive'), ('TOLERATE', 'Tolerate — absorb difference, close source'), ('DEBIT', 'Debit — log as loss, close source')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='DebitEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=20)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('responsible_party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sap_sync.party', to_field='card_code')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debits', to='stock.stockstatus')),
            ],
            options={
                'db_table': 'stock_debit_entries',
            },
        ),
    ]
