# Generated by Django 6.0.2 on 2026-03-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockstatus_is_accumulator_stockstatus_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstatus',
            name='job_work',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
