# Generated by Django 6.0.2 on 2026-02-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockstatusupdatelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstatus',
            name='total',
            field=models.DecimalField(decimal_places=2, default='0.00', editable=False, max_digits=12),
        ),
    ]
