# Generated by Django 6.0.2 on 2026-04-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockstatus_job_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstatus',
            name='rate_in_litres',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='rate',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
