# Generated by Django 6.0.2 on 2026-02-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockstatus_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstatus',
            name='total',
            field=models.DecimalField(decimal_places=2, default='0.00', editable=False, max_digits=20),
        ),
    ]
