# Generated by Django 6.0.2 on 2026-03-06 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0012_alter_domesticcontracts_po_number'),
        ('stock', '0005_alter_stockstatus_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstatus',
            name='item_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sap_sync.rmproducts', to_field='item_code'),
        ),
    ]
