# Generated by Django 6.0.2 on 2026-04-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stockstatus_rate_in_litres_alter_stockstatus_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstatus',
            name='arrival_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
