# Generated by Django 6.0.2 on 2026-03-06 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0012_alter_domesticcontracts_po_number'),
        ('stock', '0006_alter_stockstatus_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstatus',
            name='item_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sap_sync.rmproducts', to_field='item_code'),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='vendor_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sap_sync.party', to_field='card_code'),
        ),
        migrations.AlterField(
            model_name='stockstatusupdatelog',
            name='stock_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stockstatus'),
        ),
    ]
