# Generated by Django 6.0.2 on 2026-04-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stockstatus_arrival_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockstatus',
            options={'permissions': [('view_vehicle_report', 'Can view Vehicle Report')]},
        ),
    ]
