# Generated by Django 6.0.2 on 2026-03-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_stockstatus_item_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstatusupdatelog',
            name='field_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockstatusupdatelog',
            name='new_value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stockstatusupdatelog',
            name='old_value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stockstatusupdatelog',
            name='updated_by',
            field=models.CharField(max_length=50),
        ),
    ]
