# Generated by Django 6.0.2 on 2026-03-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_stockstatusupdatelog_field_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstatus',
            name='eta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockstatus',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockstatus',
            name='transporter',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockstatus',
            name='vehicle_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='status',
            field=models.CharField(choices=[('OUT_SIDE_FACTORY', 'OUT_SIDE_FACTORY'), ('ON_THE_WAY', 'ON_THE_WAY'), ('UNDER_LOADING', 'UNDER_LOADING'), ('AT_REFINERY', 'AT_REFINERY'), ('OTW_TO_REFINERY', 'OTW_TO_REFINERY'), ('KANDLA_STORAGE', 'KANDLA_STORAGE'), ('MUNDRA_PORT', 'MUNDRA_PORT'), ('ON_THE_SEA', 'ON_THE_SEA'), ('IN_CONTRACT', 'IN_CONTRACT'), ('COMPLETED', 'COMPLETED'), ('DELIVERED', 'DELIVERED'), ('IN_TRANSIT', 'IN_TRANSIT'), ('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('IN_TANK', 'IN_TANK')], max_length=50),
        ),
    ]
