# Generated by Django 6.0.2 on 2026-04-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_stockstatuschangesession_stockstatusfieldlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitentry',
            name='responsible_transporter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='debitentry',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
