# Generated by Django 6.0.2 on 2026-04-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_debitentry_responsible_transporter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitentry',
            name='type',
            field=models.CharField(choices=[('LOSS', 'Loss'), ('GAIN', 'Gain')], default='LOSS', editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
