# Generated by Django 6.0.2 on 2026-03-16 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_stockstatus_eta_stockstatus_location_and_more'),
        ('tank', '0005_tanklayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstatus',
            name='item_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tank.tankitem'),
        ),
    ]
