# Generated by Django 6.0.2 on 2026-03-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_stockstatus_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstatus',
            name='quantity_in_litre',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
