# Generated by Django 6.0.2 on 2026-04-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_debitentry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstatus',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
