# Generated by Django 6.0.2 on 2026-04-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_alter_stockstatus_arrival_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debitentry',
            old_name='responsible_party',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='debitentry',
            old_name='responsible_transporter',
            new_name='transporter',
        ),
        migrations.RemoveField(
            model_name='debitentry',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='debitentry',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='debitentry',
            name='total',
        ),
        migrations.RemoveField(
            model_name='debitentry',
            name='type',
        ),
        migrations.AddField(
            model_name='debitentry',
            name='allowed_shortage_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='debitentry',
            name='deducted_shortage_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='debitentry',
            name='deduction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='debitentry',
            name='load_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='debitentry',
            name='shortage_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='debitentry',
            name='unload_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
