# Generated by Django 6.0.2 on 2026-04-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_rename_responsible_party_debitentry_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debitentry',
            name='rate',
        ),
        migrations.AlterField(
            model_name='debitentry',
            name='allowed_shortage_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='debitentry',
            name='deducted_shortage_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='debitentry',
            name='deduction_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='debitentry',
            name='load_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='debitentry',
            name='shortage_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='debitentry',
            name='unload_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
