# Generated by Django 6.0.2 on 2026-04-25 10:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_remove_debitentry_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitentry',
            name='rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
    ]
