# Generated by Django 6.0.2 on 2026-04-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_debitentry_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitentry',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
