# Generated by Django 6.0.2 on 2026-04-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_debitentry_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitentry',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debitentry',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
