# Generated by Django 6.0.2 on 2026-04-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_debitentry_item_code_debitentry_supplier_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitentry',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
