# Generated by Django 6.0.2 on 2026-04-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_alter_debitentry_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstatus',
            name='bility_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockstatus',
            name='grpo_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
