# Generated by Django 6.0.2 on 2026-04-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_stockstatus_bility_number_stockstatus_grpo_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitentry',
            name='bility_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='debitentry',
            name='grpo_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
