# Generated by Django 6.0.2 on 2026-04-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_debitentry_bility_number_debitentry_grpo_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstatus',
            name='contract_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockstatus',
            name='contract_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
