# Generated by Django 6.0.2 on 2026-05-07 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0003_alter_domesticcontracts_options_and_more'),
        ('stock', '0020_stockstatus_contract_end_stockstatus_contract_start'),
        ('tank', '0013_rename_item_tanklog_item_code_tanklog_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractualHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('item_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tank.tankitem')),
                ('vendor_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sap_sync.party')),
            ],
            options={
                'db_table': 'contract_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
