# Generated by Django 6.0.2 on 2026-05-07 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0003_alter_domesticcontracts_options_and_more'),
        ('stock', '0021_contractualhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractualhistory',
            name='vendor_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sap_sync.party', to_field='card_code'),
        ),
    ]
