# Generated by Django 6.0.2 on 2026-05-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_alter_contractualhistory_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractualhistory',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contractualhistory',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
