# Generated by Django 6.0.2 on 2026-05-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_alter_contractualhistory_item_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractualhistory',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contractualhistory',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
