# Generated by Django 6.0.2 on 2026-05-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_contractualhistory_item_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='debitentry',
            table='shortage_entries',
        ),
    ]
