# Generated by Django 6.0.3 on 2026-05-23 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0027_alter_stockstatus_status'),
        ('tank', '0014_tankitem_id_alter_tankitem_tank_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstatus',
            name='item_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tank.tankitem', to_field='tank_item_code'),
        ),
    ]
