# Generated by Django 5.2.10 on 2026-06-13 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0029_alter_contractualhistory_id_and_more'),
        ('tank', '0016_tankitem_category_alter_tanklog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tank.tankitem', to_field='tank_item_code')),
            ],
            options={
                'db_table': 'dashboard_order',
                'ordering': ['order_number'],
            },
        ),
    ]
