# Generated by Django 5.2.10 on 2026-07-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_seed_dashboardorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstatus',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=20),
        ),
    ]
