# Generated by Django 5.2.10 on 2026-10-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0032_stockstatus_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockstatus",
            name="po_number",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
