# Generated by Django 6.0.2 on 2026-02-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=50)),
                ('card_name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=5)),
                ('u_main_group', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'Party',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('sal_factor2', models.DecimalField(decimal_places=6, max_digits=9)),
                ('u_tax_rate', models.IntegerField()),
                ('deleted', models.CharField(max_length=1)),
                ('u_variety', models.CharField(max_length=50)),
                ('sal_pack_un', models.DecimalField(decimal_places=6, max_digits=9)),
                ('u_brand', models.CharField(max_length=50)),
                ('u_unit', models.CharField(max_length=50)),
                ('u_sub_group', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='syncLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('PRT', 'Parties'), ('PRD', 'Product')], max_length=3)),
                ('status', models.CharField(choices=[('STR', 'STARTED'), ('FLD', 'FAILED'), ('SCS', 'SUCCESS')], max_length=3)),
                ('triggered_by', models.CharField(default='Manual', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('records_procesed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sync_log',
            },
        ),
    ]
