# Generated by Django 6.0.2 on 2026-03-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FGProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('sal_factor2', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('u_tax_rate', models.IntegerField(blank=True, null=True)),
                ('deleted', models.CharField(blank=True, max_length=1, null=True)),
                ('u_variety', models.CharField(blank=True, max_length=50, null=True)),
                ('sal_pack_un', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('u_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('u_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('u_sub_group', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'fg_goods',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=50, unique=True)),
                ('card_name', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=5, null=True)),
                ('u_main_group', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'Party',
            },
        ),
        migrations.CreateModel(
            name='RMProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('sal_factor2', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('u_tax_rate', models.IntegerField(blank=True, null=True)),
                ('deleted', models.CharField(blank=True, max_length=1, null=True)),
                ('u_variety', models.CharField(blank=True, max_length=50, null=True)),
                ('sal_pack_un', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('u_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('u_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('u_sub_group', models.CharField(blank=True, max_length=50, null=True)),
                ('total_trans_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('total_in_qty', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('total_out_qty', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('total_qty', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'rm_goods',
            },
        ),
        migrations.CreateModel(
            name='syncLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('PRT', 'Parties'), ('PRD', 'Products'), ('DMC', 'Domestic_Contracts')], max_length=3)),
                ('status', models.CharField(choices=[('STR', 'STARTED'), ('FLD', 'FAILED'), ('SCS', 'SUCCESS')], max_length=3)),
                ('triggered_by', models.CharField(default='Manual', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('records_procesed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sync_log',
            },
        ),
        migrations.CreateModel(
            name='DomesticContracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('contract_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('load_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('unload_qty', models.CharField(blank=True, max_length=5, null=True)),
                ('allowance', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('transporter', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=30, null=True)),
                ('bilty_no', models.CharField(blank=True, max_length=30, null=True)),
                ('bilty_date', models.DateField(blank=True, null=True)),
                ('grpo_no', models.CharField(blank=True, max_length=30, null=True)),
                ('grpo_date', models.DateField(blank=True, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=30, null=True)),
                ('basic_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('landed_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'domestic_contracts',
                'unique_together': {('po_number', 'grpo_no')},
            },
        ),
    ]
