# Generated by Django 6.0.2 on 2026-03-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fgproducts',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fgproducts',
            name='item_code',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='fgproducts',
            name='u_brand',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='fgproducts',
            name='u_sub_group',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='fgproducts',
            name='u_unit',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='fgproducts',
            name='u_variety',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
