# Generated by Django 6.0.2 on 2026-04-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0002_alter_fgproducts_category_alter_fgproducts_item_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domesticcontracts',
            options={'permissions': [('sync_po', 'Can sync PO based on GRPO')]},
        ),
        migrations.AlterModelOptions(
            name='fgproducts',
            options={'permissions': [('sync_fg', 'Can sync FG')]},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'permissions': [('sync_party', 'Can sync Party')]},
        ),
        migrations.AlterModelOptions(
            name='rmproducts',
            options={'permissions': [('sync_rm', 'Can sync RM')]},
        ),
        migrations.AlterModelOptions(
            name='synclogs',
            options={'permissions': [('sync_balance_sheet', 'Can sync Balance Sheet'), ('sync_open_grpos', 'Can sync open GRPOS'), ('sync_inventory', 'Can sync inventory')]},
        ),
    ]
