# Generated by Django 6.0.2 on 2026-02-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0002_alter_party_card_code_alter_party_card_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='party',
            table='Party',
        ),
    ]
