# Generated by Django 6.0.2 on 2026-02-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0004_alter_party_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='party',
            table='Party',
        ),
    ]
