# Generated by Django 6.0.2 on 2026-02-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0005_alter_party_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
