# Generated by Django 6.0.2 on 2026-02-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0006_alter_products_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('sal_factor2', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('u_tax_rate', models.IntegerField(blank=True, null=True)),
                ('deleted', models.CharField(blank=True, max_length=1, null=True)),
                ('u_variety', models.CharField(blank=True, max_length=50, null=True)),
                ('sal_pack_un', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('u_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('u_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('u_sub_group', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'rm_goods',
            },
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='FGProducts',
        ),
        migrations.AlterModelTable(
            name='fgproducts',
            table='fg_goods',
        ),
    ]
