# Generated by Django 6.0.2 on 2026-02-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0008_rmproducts_in_qty_rmproducts_out_qty_rmproducts_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rmproducts',
            old_name='in_qty',
            new_name='total_in_qty',
        ),
        migrations.RenameField(
            model_name='rmproducts',
            old_name='out_qty',
            new_name='total_trans_value',
        ),
    ]
