# Generated by Django 6.0.2 on 2026-03-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0009_rename_in_qty_rmproducts_total_in_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclogs',
            name='sync_type',
            field=models.CharField(choices=[('PRT', 'Parties'), ('PRD', 'Products'), ('DMC', 'Domestic_Contracts')], max_length=3),
        ),
        migrations.CreateModel(
            name='DomesticContracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('contract_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('load_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('unload_qty', models.CharField(blank=True, max_length=5, null=True)),
                ('allowance', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('transporter', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=30, null=True)),
                ('bilty_no', models.CharField(blank=True, max_length=30, null=True)),
                ('bilty_date', models.DateField(blank=True, null=True)),
                ('grpo_no', models.CharField(blank=True, max_length=30, null=True)),
                ('grpo_date', models.DateField(blank=True, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=30, null=True)),
                ('basic_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('landed_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'domestic_contracts',
                'unique_together': {('po_number', 'grpo_no')},
            },
        ),
    ]
