# Generated by Django 6.0.2 on 2026-03-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0010_alter_synclogs_sync_type_domesticcontracts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticcontracts',
            name='allowance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='domesticcontracts',
            name='basic_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='domesticcontracts',
            name='contract_qty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='domesticcontracts',
            name='contract_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='domesticcontracts',
            name='contract_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='domesticcontracts',
            name='landed_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='domesticcontracts',
            name='load_qty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='domesticcontracts',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
