# Generated by Django 6.0.2 on 2026-03-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0011_alter_domesticcontracts_allowance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticcontracts',
            name='po_number',
            field=models.CharField(max_length=50),
        ),
    ]
