# Generated by Django 6.0.2 on 2026-03-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('product_code', models.CharField(max_length=20)),
                ('vendor_code', models.CharField(max_length=50)),
                ('po_number', models.CharField(max_length=50)),
                ('po_date', models.DateField()),
                ('contract_qty', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contract_rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('load_qty', models.DecimalField(decimal_places=2, max_digits=15)),
                ('basic_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unload_qty', models.DecimalField(decimal_places=2, max_digits=15)),
                ('shortage_rec', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allow_shortage', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deduction', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deduct_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transporter_code', models.CharField(max_length=50)),
                ('transporter_name', models.CharField(max_length=200)),
                ('bility_number', models.CharField(max_length=50)),
                ('bility_date', models.DateField()),
                ('frieght_rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('freight_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('grpo_date', models.DateField()),
                ('grpo_number', models.CharField(max_length=50)),
                ('brokerage_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('brokerage_rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('invoice_number', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.IntegerField(default=0)),
                ('Completed', models.IntegerField(default=0)),
            ],
        ),
    ]
