# Generated by Django 6.0.2 on 2026-03-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='domesticreports',
            table='old_domestic_contract',
        ),
    ]
