# Generated by Django 6.0.2 on 2026-03-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_domesticreports_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domesticreports',
            old_name='deduction',
            new_name='deduction_qty',
        ),
        migrations.RenameField(
            model_name='domesticreports',
            old_name='shortage_rec',
            new_name='shortage',
        ),
        migrations.AddField(
            model_name='domesticreports',
            name='contract_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterModelTable(
            name='domesticreports',
            table='contracts',
        ),
    ]
