# Generated by Django 6.0.2 on 2026-03-30 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_rename_deduction_domesticreports_deduction_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domesticreports',
            old_name='deduct_amount',
            new_name='deduction_amount',
        ),
    ]
