# Generated by Django 6.0.2 on 2026-03-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_rename_deduct_amount_domesticreports_deduction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticreports',
            name='status',
            field=models.CharField(choices=[('CONTRACT', 'CONTRACT'), ('PO', 'PO'), ('MAIL_APPROVAL', 'MAIL_APPROVAL'), ('PAYMENT', 'PAYMENT'), ('TPT/LOADING', 'TPT/LOADING'), ('IN_TRANSIT', 'IN_TRANSIT'), ('FACTORY', 'FACTORY'), ('RECIEVED', 'RECIEVED')], max_length=50),
        ),
    ]
