# Generated by Django 6.0.2 on 2026-04-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_domesticreports_allow_shortage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domesticreports',
            name='brokerage_rate',
        ),
    ]
