# Generated by Django 6.0.2 on 2026-04-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_remove_domesticreports_brokerage_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domesticreports',
            options={'permissions': [('add_contract', 'Can add Contract'), ('edit_contract', 'Can  Contract'), ('delete_contract', 'Can delete Contract'), ('read_contract', 'Can read Contract')]},
        ),
    ]
