# Generated by Django 6.0.2 on 2026-04-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_alter_domesticreports_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domesticreports',
            options={},
        ),
    ]
