# Generated by Django 5.2.10 on 2026-08-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_alter_domesticreports_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticContractDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('po_number', models.CharField(db_index=True, max_length=50)),
                ('grpo_no', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('grpo_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('RECEIVED', 'RECEIVED'), ('IN_TRANSIT', 'IN_TRANSIT'), ('PENDING', 'PENDING')], max_length=20, null=True)),
                ('supplier', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('del_terms', models.CharField(blank=True, choices=[('FOR', 'FOR'), ('EXW', 'EXW')], max_length=10, null=True)),
                ('contract_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('load_qty_mts', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('inv_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('basic_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unload_qty_mts', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('unload_qty_ltr', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('rate_in_sap_unloading', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('shortage_recd_mts', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('allow_shortage_mts', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('deduction_qty_mts', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('deduct_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('freight_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('freight_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('brokerage_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('brokerage_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('bilty_charges', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('cost_per_mt', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('cost_per_kl', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('cost_per_ltr', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('transporter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=30, null=True)),
                ('bilty_number', models.CharField(blank=True, max_length=30, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'domestic_contract_details',
                'ordering': ['-invoice_date', 'invoice_no'],
                'indexes': [models.Index(fields=['supplier'], name='domestic_co_supplie_31588c_idx'), models.Index(fields=['item'], name='domestic_co_item_727ac7_idx'), models.Index(fields=['invoice_date'], name='domestic_co_invoice_465d07_idx')],
            },
        ),
    ]
