# Generated by Django 6.0.2 on 2026-04-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_exim_rates', 'Can see Exim Rates')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
