# Generated by Django 6.0.2 on 2026-04-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_systemaccess_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_exim_rates', 'Can see Exim Rates'), ('view_director_report', 'Can See Director Report'), ('add_opening_rate', 'Can Add Opening Rate')]},
        ),
    ]
