# Generated by Django 5.2.10 on 2026-07-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_exim_rates', 'Can see Exim Rates'), ('view_director_report', 'Can See Director Report'), ('add_opening_rate', 'Can Add Opening Rate'), ('view_customer_balance_sheet', 'Can View Customer Balance Sheet'), ('view_bank_accounts', 'Can View bank Accounts'), ('view_bank_closing', 'Can View bank closing')]},
        ),
    ]
