# Generated by Django 5.2.10 on 2026-08-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_systemaccess_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systemaccess",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("view_exim_rates", "Can see Exim Rates"),
                    ("view_director_report", "Can See Director Report"),
                    ("add_opening_rate", "Can Add Opening Rate"),
                    ("view_bank_accounts", "Can View bank Accounts"),
                    ("view_bank_closing", "Can View bank closing"),
                    ("view_customer_balance_sheet", "Can View Customer Balance Sheet"),
                    ("view_customer_outstanding", "Can view Customer Outstanding"),
                    ("view_customer_ledger", "Can view Customer Ledger"),
                    ("view_customer_aging", "Can view Customer Aging"),
                    ("view_open_ars", "Can view Open ARs"),
                    ("view_vendor_outstanding", "Can view Vendor Outstanding"),
                    ("view_vendor_ledger", "Can view Vendor Ledger"),
                    ("view_open_aps", "Can view Open APs"),
                    ("view_open_pos", "Can view Open POs"),
                    ("view_finance_dashboard", "Can view Finance Dashboard"),
                    ("view_bank_ledger", "Can view Bank Ledger"),
                ],
            },
        ),
    ]
