# Generated by Django 5.2.10 on 2026-08-27 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlanningUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        help_text="First day of the planned month, e.g. 2026-09-01"
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Banner text from the sheet",
                        max_length=255,
                    ),
                ),
                ("source_file", models.CharField(max_length=255)),
                ("uploaded_by", models.CharField(blank=True, max_length=150)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("row_count", models.IntegerField(default=0)),
                (
                    "commodity_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "premium_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "ecom_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
            ],
            options={
                "db_table": "planning_uploads",
                "ordering": ["-month", "-version"],
                "permissions": [("upload_planning", "Can upload monthly planning")],
                "unique_together": {("month", "version")},
            },
        ),
        migrations.CreateModel(
            name="PlanningRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50)),
                ("brand", models.CharField(blank=True, db_index=True, max_length=100)),
                ("head", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "sub_category",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("sku", models.CharField(blank=True, max_length=255)),
                (
                    "per_ltrs",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "ltrs_per_box",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "case_pack",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "commodity_monthly",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "commodity_w1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "commodity_w2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "commodity_w3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "commodity_w4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "premium_monthly",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "premium_w1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "premium_w2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "premium_w3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "premium_w4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "ecom_planning",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_planning",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("source_row", models.IntegerField(blank=True, null=True)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="planning.planningupload",
                    ),
                ),
            ],
            options={
                "db_table": "planning_rows",
                "ordering": ["-total_planning", "code"],
                "indexes": [
                    models.Index(
                        fields=["upload", "category"],
                        name="planning_ro_upload__d7f574_idx",
                    ),
                    models.Index(
                        fields=["upload", "sub_category"],
                        name="planning_ro_upload__1b8c21_idx",
                    ),
                ],
            },
        ),
    ]
