# Generated by Django 5.2.10 on 2026-08-27 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planningupload",
            options={"ordering": ["-month", "-version"]},
        ),
    ]
