# Generated by Django 6.0.2 on 2026-03-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=125)),
                ('factory_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('packing_cost_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('with_gst_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('with_gst_ltr', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('created_by', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('commodity_name', 'date')},
            },
        ),
    ]
