# Generated by Django 6.0.2 on 2026-03-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_price', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailyprice',
            table='daily_prices',
        ),
    ]
