# Generated by Django 6.0.2 on 2026-03-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_price', '0002_alter_dailyprice_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='JivoRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
    ]
