# Generated by Django 6.0.2 on 2026-03-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_price', '0003_jivorates'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jivorates',
            table='jivo_rates',
        ),
    ]
