# Generated by Django 6.0.2 on 2026-03-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_price', '0004_alter_jivorates_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='jivorates',
            name='commodity',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='jivorates',
            name='pack_type',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='jivorates',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
