# Generated by Django 6.0.2 on 2026-03-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_price', '0005_jivorates_commodity_jivorates_pack_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jivorates',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
