# Generated by Django 6.0.2 on 2026-03-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_price', '0006_alter_jivorates_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jivorates',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
