# Generated by Django 6.0.2 on 2026-04-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_price', '0007_alter_jivorates_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprice',
            options={'permissions': [('fetch_daily_prices', 'Can fetch Daily Prices'), ('view_daily_price_graph', 'Can see daily price grpah')]},
        ),
        migrations.AlterModelOptions(
            name='jivorates',
            options={'permissions': [('fetch_jivo_rate', 'Can fetch jivo rates'), ('daily_price_graph', 'Can see daily price graph')]},
        ),
    ]
