# Generated by Django 6.0.2 on 2026-04-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_price', '0008_alter_dailyprice_options_alter_jivorates_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprice',
            options={'permissions': [('fetch_daily_price', 'Can fetch Daily Prices'), ('view_daily_price_graph', 'Can see daily price grpah')]},
        ),
        migrations.AlterModelOptions(
            name='jivorates',
            options={'permissions': [('fetch_jivo_rate', 'Can fetch jivo rates')]},
        ),
    ]
