# Generated by Django 6.0.2 on 2026-04-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_price', '0009_alter_dailyprice_options_alter_jivorates_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jivorates',
            options={'permissions': [('fetch_jivo_rates', 'Can fetch jivo rates')]},
        ),
    ]
