# Generated by Django 5.2.10 on 2026-07-18 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackingMargins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_name', models.CharField(max_length=100)),
                ('packing_margin', models.DecimalField(decimal_places=5, max_digits=10)),
                ('created_by', models.CharField(max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'packing_margins',
            },
        ),
        migrations.CreateModel(
            name='CommodityMarginRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=100)),
                ('margin_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factory_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'commodity_margin_rates',
                'unique_together': {('commodity', 'factory_kg', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='BasicRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('commodity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.commoditymarginrates')),
                ('packing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.packingmargins')),
            ],
            options={
                'db_table': 'basic_rates',
            },
        ),
    ]
