# Generated by Django 5.2.10 on 2026-07-18 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=100)),
                ('margin_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'commodity_rates',
            },
        ),
        migrations.RemoveField(
            model_name='basicrates',
            name='commodity',
        ),
        migrations.CreateModel(
            name='MarketRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('commodity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.commoditymargin')),
            ],
            options={
                'db_table': 'market_rates',
                'unique_together': {('commodity', 'factory_kg', 'date')},
            },
        ),
        migrations.AddField(
            model_name='basicrates',
            name='market_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.marketrates'),
        ),
        migrations.DeleteModel(
            name='CommodityMarginRates',
        ),
    ]
