# Generated by Django 5.2.10 on 2026-07-18 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_commoditymargin_remove_basicrates_commodity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketrates',
            unique_together=set(),
        ),
    ]
