# Generated by Django 5.2.10 on 2026-07-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_alter_marketrates_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicrates',
            old_name='basic_price',
            new_name='basic_price_kg',
        ),
    ]
