# Generated by Django 5.2.10 on 2026-07-18 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_rename_basic_price_basicrates_basic_price_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('ltr', 'Ltr')], max_length=3)),
                ('conversion_factor', models.DecimalField(decimal_places=5, max_digits=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('commodities', models.ManyToManyField(blank=True, to='rates.commoditymargin')),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.packingmargins')),
            ],
            options={
                'db_table': 'pack_sizes',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('market_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_rates', to='rates.marketrates')),
                ('pack_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.packsize')),
            ],
            options={
                'db_table': 'pack_rates',
            },
        ),
    ]
