# Generated by Django 5.2.10 on 2026-07-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0005_packsize_packrates'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoditymargin',
            name='freight_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='marketrates',
            name='factory_kg_freight',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
            preserve_default=False,
        ),
    ]
