# Generated by Django 5.2.10 on 2026-07-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0006_commoditymargin_freight_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditymargin',
            name='freight_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=5, null=True),
        ),
    ]
