# Generated by Django 6.0.2 on 2026-02-26 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TankItem',
            fields=[
                ('tank_item_code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('tank_item_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tank_item',
            },
        ),
        migrations.CreateModel(
            name='TankData',
            fields=[
                ('tank_code', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('tank_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tank.tankitem')),
            ],
            options={
                'db_table': 'tank_data',
            },
        ),
    ]
