# Generated by Django 6.0.2 on 2026-03-19 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sap_sync', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankItem',
            fields=[
                ('tank_item_code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('tank_item_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tank_item',
            },
        ),
        migrations.CreateModel(
            name='TankData',
            fields=[
                ('tank_code', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('tank_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tank.tankitem')),
            ],
            options={
                'db_table': 'tank_data',
            },
        ),
        migrations.CreateModel(
            name='TankLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_added', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity_remaining', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('is_exhausted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tank.tankitem')),
                ('stock_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockstatus')),
                ('tank_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tank.tankdata')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sap_sync.party')),
            ],
            options={
                'db_table': 'tank_layer',
            },
        ),
        migrations.CreateModel(
            name='TankLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('INWARD', 'INWARD'), ('OUTWARD', 'OUTWARD')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('stock_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.stockstatus')),
                ('tank_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tank.tankdata')),
                ('tank_layer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tank.tanklayer')),
            ],
            options={
                'db_table': 'tank_logs',
            },
        ),
        migrations.CreateModel(
            name='TankLogConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tank_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='tank.tanklayer')),
                ('tank_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='tank.tanklog')),
            ],
            options={
                'db_table': 'tank_log_consumption',
            },
        ),
    ]
