# Generated by Django 6.0.2 on 2026-02-27 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankdata',
            name='item_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tank.tankitem'),
        ),
    ]
