# Generated by Django 6.0.2 on 2026-02-25 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tankitem',
            old_name='tanks_item_name',
            new_name='tank_item_name',
        ),
    ]
