# Generated by Django 5.2.10 on 2026-03-24 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanklog',
            name='destination_tank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_logs', to='tank.tankdata'),
        ),
        migrations.AlterField(
            model_name='tanklayer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tanklog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tanklog',
            name='log_type',
            field=models.CharField(choices=[('INWARD', 'INWARD'), ('OUTWARD', 'OUTWARD'), ('TRANSFER', 'TRANSFER')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tanklog',
            name='tank_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tank.tankdata'),
        ),
        migrations.AlterField(
            model_name='tanklogconsumption',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
