# Generated by Django 6.0.2 on 2026-02-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0002_rename_tanks_item_name_tankitem_tank_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tankdata',
            old_name='current_capacit',
            new_name='current_capacity',
        ),
    ]
