# Generated by Django 6.0.2 on 2026-03-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0002_tanklog_destination_tank_alter_tanklayer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanklayer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tanklog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tanklogconsumption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
