# Generated by Django 6.0.2 on 2026-02-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0003_rename_current_capacit_tankdata_current_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankdata',
            name='tank_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tankitem',
            name='tank_item_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
