# Generated by Django 6.0.2 on 2026-03-06 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0003_alter_tankdata_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankdata',
            name='item_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tank.tankitem'),
        ),
    ]
