# Generated by Django 6.0.2 on 2026-03-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0003_alter_tanklayer_id_alter_tanklog_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanklog',
            name='destination_tank',
        ),
        migrations.RemoveField(
            model_name='tanklog',
            name='tank_code',
        ),
    ]
