# Generated by Django 6.0.2 on 2026-03-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0004_remove_tanklog_destination_tank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanklog',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='tanklog',
            name='tank_layer',
        ),
    ]
