# Generated by Django 6.0.2 on 2026-03-16 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0012_alter_domesticcontracts_po_number'),
        ('stock', '0009_stockstatus_eta_stockstatus_location_and_more'),
        ('tank', '0004_alter_tankdata_item_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tank.tankitem')),
                ('stock_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockstatus')),
                ('tank_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tank.tankdata')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sap_sync.party')),
            ],
        ),
    ]
