# Generated by Django 6.0.2 on 2026-02-25 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0004_alter_tankdata_tank_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankdata',
            name='current_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tankdata',
            name='item_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tank.tankitem'),
        ),
    ]
