# Generated by Django 6.0.2 on 2026-03-16 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_stockstatus_item_code'),
        ('tank', '0005_tanklayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanklayer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tanklayer',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tanklayer',
            name='is_exhausted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tanklayer',
            name='qauntity_added',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tanklayer',
            name='quantity_remaining',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterModelTable(
            name='tanklayer',
            table='tank_layer',
        ),
        migrations.CreateModel(
            name='TankLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('INWARD', 'INWARD'), ('OUTWARD', 'OUTWARD')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('stock_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.stockstatus')),
                ('tank_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tank.tankdata')),
                ('tank_layer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tank.tanklayer')),
            ],
            options={
                'db_table': 'tank_logs',
            },
        ),
        migrations.CreateModel(
            name='TankLogConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tank_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='tank.tanklayer')),
                ('tank_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='tank.tanklog')),
            ],
            options={
                'db_table': 'tank_log_consumption',
            },
        ),
    ]
