# Generated by Django 6.0.2 on 2026-03-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0005_remove_tanklog_remarks_remove_tanklog_tank_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanklog',
            name='party',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tanklog',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tanklog',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
