# Generated by Django 6.0.2 on 2026-03-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0006_tanklayer_created_at_tanklayer_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tanklayer',
            old_name='qauntity_added',
            new_name='quantity_added',
        ),
    ]
