# Generated by Django 6.0.2 on 2026-03-27 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0002_alter_fgproducts_category_alter_fgproducts_item_code_and_more'),
        ('tank', '0006_tanklog_party_tanklog_rate_tanklog_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanklog',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sap_sync.party'),
        ),
    ]
