# Generated by Django 6.0.2 on 2026-03-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0007_rename_qauntity_added_tanklayer_quantity_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanklog',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
