# Generated by Django 6.0.2 on 2026-03-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0007_alter_tanklog_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanklog',
            name='party',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
