# Generated by Django 6.0.2 on 2026-04-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0008_alter_tanklog_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankdata',
            name='tank_type',
            field=models.CharField(blank=True, choices=[('TANK', 'TANK'), ('TOTES', 'TOTES')], default='TANK', max_length=10, null=True),
        ),
    ]
