# Generated by Django 6.0.2 on 2026-04-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0009_tankdata_tank_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanklogconsumption',
            name='tank_layer',
        ),
        migrations.RemoveField(
            model_name='tanklogconsumption',
            name='tank_log',
        ),
        migrations.AlterModelOptions(
            name='tankdata',
            options={'permissions': [('view_itemwise_average', 'Can See Item Average')]},
        ),
        migrations.DeleteModel(
            name='TankLayer',
        ),
        migrations.DeleteModel(
            name='TankLogConsumption',
        ),
    ]
