# Generated by Django 6.0.2 on 2026-04-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0010_remove_tanklogconsumption_tank_layer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanklog',
            name='item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
