# Generated by Django 6.0.2 on 2026-04-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0011_tanklog_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanklog',
            name='arrival',
            field=models.DateField(blank=True, null=True),
        ),
    ]
