# Generated by Django 6.0.2 on 2026-04-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0012_tanklog_arrival'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tanklog',
            old_name='item',
            new_name='item_code',
        ),
        migrations.AddField(
            model_name='tanklog',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
