# Generated by Django 5.2.10 on 2026-06-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0015_alter_tankdata_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankitem',
            name='category',
            field=models.CharField(blank=True, choices=[('SOYABEAN', 'SOYABEAN'), ('OILVE', 'OILVE'), ('CANOLA', 'CANOLA'), ('MUSTARD', 'MUSTARD'), ('GROUNDNUT', 'GROUNDNUT'), ('GHEE', 'GHEE'), ('SUNFLOWER', 'SUNFLOWER'), ('RICE BRAN', 'RICE BRAN'), ('COCONUT', 'COCONUT'), ('SESAME', 'SESAME'), ('EXTRA VIRGIN', 'EXTRA VIRGIN'), ('COTTON SEED', 'COTTON SEED'), ('BLENDED', 'BLENDED')], null=True),
        ),
        migrations.AlterField(
            model_name='tanklog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
