# Generated by Django 6.0.2 on 2026-03-09 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceLicenseHeaders',
            fields=[
                ('license_no', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('issue_date', models.DateField()),
                ('import_validity', models.DateField()),
                ('export_validity', models.DateField()),
                ('import_in_mts', models.DecimalField(decimal_places=3, max_digits=8)),
                ('cif_value_inr', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cif_value_usd', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cif_exchange_rate', models.DecimalField(decimal_places=3, max_digits=8)),
                ('export_in_mts', models.DecimalField(decimal_places=3, max_digits=8)),
                ('fob_value_inr', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fob_value_usd', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fob_exhange_rate', models.DecimalField(decimal_places=3, max_digits=8)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close')], max_length=10)),
            ],
            options={
                'db_table': 'advance_license_headers',
            },
        ),
        migrations.CreateModel(
            name='AdvanceLicenseLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boe_No', models.CharField(max_length=50)),
                ('boe_value_usd', models.DecimalField(decimal_places=3, max_digits=12)),
                ('shipping_bill_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('sb_value_usd', models.DecimalField(decimal_places=3, max_digits=12)),
                ('import_in_mts', models.DecimalField(decimal_places=3, max_digits=8)),
                ('export_in_mts', models.DecimalField(decimal_places=3, max_digits=8)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=12)),
                ('license_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lincense_lines', to='license.advancelicenseheaders')),
            ],
            options={
                'db_table': 'advance_license_lines',
            },
        ),
    ]
