# Generated by Django 6.0.2 on 2026-03-13 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DFIALicenseHeader',
            fields=[
                ('file_no', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('issue_date', models.DateField()),
                ('export_validity', models.DateField()),
                ('export_in_mts', models.DecimalField(decimal_places=3, max_digits=8)),
                ('fob_value_inr', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fob_value_usd', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fob_exchange_rate', models.DecimalField(decimal_places=3, max_digits=8)),
                ('import_validity', models.DateField()),
                ('import_in_mts', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cif_value_inr', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cif_value_usd', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cif_exchange_rate', models.DecimalField(decimal_places=3, max_digits=8)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dfia_license_header',
            },
        ),
        migrations.CreateModel(
            name='DFIALicenseLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boe_no', models.CharField(max_length=50)),
                ('shipping_bill_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('to_be_imported_in_mts', models.DecimalField(decimal_places=3, max_digits=8)),
                ('exported_in_mts', models.DecimalField(decimal_places=3, max_digits=8)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=8)),
                ('sb_value_inr', models.DecimalField(decimal_places=3, max_digits=15)),
                ('license_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dfia_license_lines', to='license.dfialicenseheader')),
            ],
            options={
                'db_table': 'dfia_license_lines',
            },
        ),
    ]
