# Generated by Django 6.0.2 on 2026-04-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_dfialicenseheader_dfialicenselines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancelicenselines',
            options={'permissions': [('view_line_insights', 'Can see line Insights')]},
        ),
        migrations.AlterModelOptions(
            name='dfialicenselines',
            options={'permissions': [('view_dfia_line_insights', 'Can see DFIA line Insights')]},
        ),
    ]
