# Generated by Django 6.0.2 on 2026-04-15 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_alter_advancelicenselines_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancelicenseheaders',
            name='export_in_mts',
        ),
        migrations.RemoveField(
            model_name='advancelicenseheaders',
            name='import_in_mts',
        ),
        migrations.AddField(
            model_name='advancelicenseheaders',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='advancelicenseheaders',
            name='to_be_exported',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advancelicenseheaders',
            name='total_export',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advancelicenseheaders',
            name='total_import',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AdvanceLicenseExportLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_bill_no', models.CharField(max_length=50)),
                ('sb_value_usd', models.DecimalField(decimal_places=3, max_digits=12)),
                ('export_in_mts', models.DecimalField(decimal_places=3, max_digits=8)),
                ('license_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_lines', to='license.advancelicenseheaders')),
            ],
            options={
                'db_table': 'advance_license_export_lines',
            },
        ),
        migrations.CreateModel(
            name='AdvanceLicenseImportLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boe_No', models.CharField(max_length=50)),
                ('boe_value_usd', models.DecimalField(decimal_places=3, max_digits=12)),
                ('boe_date', models.DateField()),
                ('import_in_mts', models.DecimalField(decimal_places=3, max_digits=8)),
                ('license_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_lines', to='license.advancelicenseheaders')),
            ],
            options={
                'db_table': 'advance_license_import_lines',
            },
        ),
        migrations.DeleteModel(
            name='AdvanceLicenseLines',
        ),
    ]
