# Generated by Django 6.0.2 on 2026-04-15 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_remove_advancelicenseheaders_export_in_mts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfialicenseheader',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='dfialicenseheader',
            name='to_be_imported',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='dfialicenseheader',
            name='total_export',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='dfialicenseheader',
            name='total_import',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='advancelicenseheaders',
            name='to_be_exported',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='advancelicenseheaders',
            name='total_export',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='advancelicenseheaders',
            name='total_import',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.CreateModel(
            name='DFIALicenseExportLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_bill_no', models.CharField(max_length=50)),
                ('sb_value_usd', models.DecimalField(decimal_places=3, max_digits=12)),
                ('export_in_mts', models.DecimalField(decimal_places=3, max_digits=8)),
                ('license_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dfia_export_lines', to='license.dfialicenseheader')),
            ],
            options={
                'db_table': 'dfia_license_export_lines',
            },
        ),
        migrations.CreateModel(
            name='DFIALicenseImportLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boe_no', models.CharField(max_length=50)),
                ('boe_value_usd', models.DecimalField(decimal_places=3, max_digits=12)),
                ('boe_date', models.DateField()),
                ('import_in_mts', models.DecimalField(decimal_places=3, max_digits=8)),
                ('license_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dfia_license_lines', to='license.dfialicenseheader')),
            ],
            options={
                'db_table': 'dfia_license_import_lines',
            },
        ),
        migrations.DeleteModel(
            name='DFIALicenseLines',
        ),
    ]
