# Generated by Django 6.0.2 on 2026-04-15 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_dfialicenseheader_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfialicenseimportlines',
            name='license_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dfia_import_lines', to='license.dfialicenseheader'),
        ),
    ]
