# Generated by Django 6.0.2 on 2026-04-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0006_alter_dfialicenseimportlines_license_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dfialicenseheader',
            name='export_in_mts',
        ),
        migrations.RemoveField(
            model_name='dfialicenseheader',
            name='import_in_mts',
        ),
    ]
