# Generated by Django 6.0.2 on 2026-04-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0007_remove_dfialicenseheader_export_in_mts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancelicenseexportlines',
            name='sb_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dfialicenseexportlines',
            name='sb_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
