# Generated by Django 6.0.2 on 2026-04-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0008_advancelicenseexportlines_sb_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancelicenseheaders',
            name='total_import_quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='advancelicenseheaders',
            name='total_to_be_exported_quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
    ]
