# Generated by Django 6.0.2 on 2026-04-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0009_advancelicenseheaders_total_import_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancelicenseheaders',
            name='total_to_be_exported_quantity',
        ),
    ]
