# Generated by Django 6.0.2 on 2026-04-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0010_remove_advancelicenseheaders_total_to_be_exported_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfialicenseheader',
            name='total_export_quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
    ]
