# Generated by Django 6.0.2 on 2026-04-25 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0012_advancelicenseexportlines_linked_import_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfialicenseimportlines',
            name='linked_export_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_export_lines', to='license.dfialicenseexportlines'),
        ),
    ]
